install.packages("httr")
install.packages("git2r")
install.packages("devtools")
install.packages("rgdal")
devtools::install_github("iobis/obistools")
install.packages("RCurl")
install.packages("finch")
install.packages("dplyr")
install.packages("data.table")
install.packages("ggplot2")
install.packages("rmarkdown")
install.packages("knitr")
install.packages("leaflet")
install.packages("stringr")

