---
title: "EMODnet Biology Dataset Overview"
output: html_document
---
  
```{r  echo=FALSE, results='asis'}

if("datasummary" %in% names(IPTreport)) 
      if(nrow(IPTreport$datasummary) > 0) {
  cat("<h2>Overview&nbsp;of&nbsp;event&nbsp;and&nbsp;occurrence&nbsp;records</h2>")
  kable(IPTreport$datasummary)
}  

```


```{r  echo=FALSE, results='asis'}

if("mofsummary" %in% names(IPTreport)) 
    if(nrow(IPTreport$mofsummary) > 0) {
  cat("<h2>Overview of the measurement or fact records</h2>")
  kable(IPTreport$mofsummary)
}  

```


```{r  echo=FALSE, results='asis'}

if("mofsummary_values" %in% names(IPTreport)) 
  if(nrow(IPTreport$mofsummary_values) > 0 ) 
  { cat("<h2>Overview of standerdised measurement values</h2>")
  kable(IPTreport$mofsummary_values)
}  

```


```{r  echo=FALSE, results='asis'}

if("plot_coordinates" %in% names(IPTreport)) {
  cat("<h2>Geographical cover of the dataset</h2>")
  
  if ("plot_coordinates"  %in% names(IPTreport)  ) 
    if (is.data.frame(IPTreport$plot_coordinates)) 
      if (nrow(IPTreport$plot_coordinates)> 0 )
      {IPTreport$plots<-IPTreport$plot_coordinates %>% mutate (decimalLatitude = round(decimalLatitude,1),decimalLongitude = round (decimalLongitude, 1)) %>% 
        select(Lat=decimalLatitude,Lon=decimalLongitude, quality) %>% distinct()
      
      pal=function(x){ifelse(x=='OK',"Green",ifelse(x=='Check Depth',"Blue",ifelse(x=='On Land',"Red","Black")))}
      
      leaflet(IPTreport$plots) %>% 
        addProviderTiles("Esri.OceanBasemap", options = providerTileOptions(maxZoom = 10)) %>%  
        addCircleMarkers(popup=~formatLabel(IPTreport$plots),~Lon, ~Lat,  radius = 3, color = ~pal(quality))
      
      }
  
  else
    leaflet() %>% addProviderTiles("Esri.OceanBasemap") 
  
}  

```







```{r  echo=FALSE, results='asis'}

if("dates_plot" %in% names(IPTreport)) {  if (length(unique(IPTreport$dates_plot$year)) > 0 ) {
  years<-unique(c(min(IPTreport$dates_plot$year), median(IPTreport$dates_plot$year), max(IPTreport$dates_plot$year)))
  cat("<h2>Temporal cover of the dataset</h2>")
  
  ggplot2::ggplot(IPTreport$dates_plot, aes(x=year)) + 
    geom_histogram(binwidth=1, color=("red"), fill=("red")) +
    scale_x_continuous(labels = years, breaks = years) +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          text = element_text(size=20),
          panel.background = element_rect(fill = "transparent") # bg of the panel
          , panel.grid.major = element_blank() # get rid of major grid
          , panel.grid.minor = element_blank() # get rid of minor grid
          , plot.background = element_rect(fill = "transparent"))
  
  }}

```

```{r  echo=FALSE, results='asis'}
   if(length(IPTreport$startdate)>0) {
  cat("date range according to metadata:" , IPTreport$startdate , "-", IPTreport$enddate)
   }

```




