---
title: "EMODnet Biology QC report"
output: html_document
---
  
```{r  echo=FALSE, results='asis'}

if("general_issues" %in% names(IPTreport$dtb)) 
   if(nrow(IPTreport$dtb$general_issues) > 0) {
  cat("<h2>Overview of all issues</h2>")
  kable(IPTreport$dtb$general_issues)
}  

```



```{r  echo=FALSE, results='asis'}

if("mof_issues" %in% names(IPTreport$dtb)) 
     if(nrow(IPTreport$dtb$mof_issues) > 0) {
  cat("<h2>Overview of potential issues with MoF records</h2>")
  kable(IPTreport$dtb$mof_issues)
}  

```




```{r  echo=FALSE, results='asis'}

if ("plot_coordinates"  %in% names(IPTreport)  ) {
  if (is.data.frame(IPTreport$plot_coordinates)) { 
    if (nrow(IPTreport$plot_coordinates)> 0 ) {
      cat("<h2>Issues on Map</h2>")
      
      IPTreport$plot_coordinates<-  suppressWarnings(dplyr::select(IPTreport$plot_coordinates,decimalLatitude,decimalLongitude, quality, one_of(c("eventID","occurrenceID", "coordinateUncertaintyInMeters"))))
      
      IPTreport$plot_coordinates<- IPTreport$plot_coordinates %>% filter(quality != "OK")
      
        pal=function(x){ifelse(x=='OK',"Green",ifelse(x=='Check Depth',"Blue", ifelse (x == 'Marine Taxa on Land', 'Red', ifelse(x=='On Land', "Yellow","Black"))))}
      
      
      leaflet(IPTreport$plot_coordinates) %>%
        addProviderTiles("Esri.OceanBasemap", options = providerTileOptions(maxZoom = 10)) %>%
        addCircleMarkers(popup=~formatLabel(IPTreport$plot_coordinates),~decimalLongitude, ~decimalLatitude,  radius = 3, color = ~pal(quality))
      
    }  else {
      leaflet() %>% addProviderTiles("Esri.OceanBasemap") 
    }}  }

```




```{r  echo=FALSE, results='asis'}

   if("taxa" %in% names(IPTreport$dtb)) {
     noinworms <- IPTreport$dtb$taxa %>% filter(is.na(scientificNameMatch)) %>% select (scientificName, scientificNameID, status, count)
     if (nrow (noinworms)>0)
  cat("<h2>Overview unmatched taxa</h2>")
  kable(noinworms)
}

```
 
 
```{r  echo=FALSE, results='asis'}

   if("MarTaxaonLand" %in% names(IPTreport)) {
     onland <- IPTreport$MarTaxaonLand %>% filter(!is.na(scientificNameMatch)) %>% group_by (scientificNameMatch, scientificNameID, kingdom, class, status, isMarine, isBrackish , isFreshwater , isTerrestrial) %>% summarise (count =n())
     if (nrow (onland)>0) {
  cat("<h2>Marine taxa on land</h2>")
  kable(onland)
     }}

```








