---
title: "EMODnet Biology QC report"
output: html_document
---

```{r  echo=FALSE, results='asis'}

if (exists("all_report_issues")) {
cat("<h2>Overview</h2>")
if (is.data.frame(all_report_issues)) {

kable(all_report_issues)

} else
print(all_report_issues)  
  }

```


```{r  echo=FALSE , results='asis'}


if (exists("all_report_issues")) {
if (is.data.frame(all_report_issues)) {

cat("You can find the records with issus in the files: <br/>")
 kable(files)  
}}      



if (exists("mofreport")) {
if (is.data.frame(mofreport)) {
if (nrow(mofreport)> 0 )	{

cat("
<br/>
<br/>
<h2>eMoF report</h2>
  ")

kable(mofreport) 

}}}



cat("
<br/>
<br/>
<h2> plots</h2>
  ")



if (is.data.frame(IPTreport$plot_coordinates)) {
if (nrow(IPTreport$plot_coordinates)> 0 )	{

cat("

#### All records

  ")
  
if (nrow(IPTreport$plot_coordinates) < 10000) {  

    leaflet(IPTreport$plot_coordinates) %>%
    addProviderTiles("Esri.OceanBasemap") %>%
    addCircleMarkers(~decimalLongitude, ~decimalLatitude,  radius = 3, weight = 1, fillColor = "#FF368B", color = "#FF368B", opacity = 1, fillOpacity = 0.1)
} else 
{
  
  plot_map(IPTreport$plot_coordinates, zoom = TRUE)
}
         
          
  
}}








if (is.data.frame(IPTreport$dates_plot)) {
if (nrow(IPTreport$dates_plot)> 0 )	{


cat("

#### Temporal cover

The following plot is a historgram of all years provided in the dataset

  ")


ggplot(IPTreport$dates_plot, aes(x=year)) + 
  geom_histogram(binwidth=1, color="red", fill="blue")  
  


}}
```










