name: Update BODC tables used in the package

on:
  # Scheduled to run on the 1st of each month
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight UTC on the 1st of each month
  # For testing purposes, also trigger on push to main branch
  push:
    branches:
      - develop

jobs:
  generate-table:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      # Step 3: Install required dependencies
      - name: Install dependencies
        run: |
          pip install pandas pysema requests numpy

      # Step 4: Run the Python script that generates the table
      - name: Run table generator script
        run: python files/BODC_tables_generator.py

      # Step 5: Set up R environment
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2


      # Step 7: Read the CSV files in R and run the usethis::use_data() commands
      - name: Process CSV files with R
        run: |
          BODCunits <- read.csv("files/BODCunits.csv")
          BODCvalues <- read.csv("files/BODCvalues.csv")
          BODCparameters <- read.csv("files/BODCparameters.csv")
          usethis::use_data(BODCunits, overwrite = TRUE)
          usethis::use_data(BODCvalues, overwrite = TRUE)
          usethis::use_data(BODCparameters, overwrite = TRUE)

      # Step 8: Run devtools::document() to update R package documentation
      - name: Update R documentation
        run: |
          devtools::document()
